### ISSUE TITLE
prisma warning

### ISSUE THREAD

**Issue by COOK1EK1W1** [COOK1EK1W1/deadline-web#25]
new clients being generated with every db call
![Screenshot 2023-09-21 at 13 20 07](https://github.com/COOK1EK1W1/deadline-web/assets/61564769/a9525fd9-fc34-4c26-ae21-f1e6a58d8af8)

**Comment by murtaza135** [comment]
this is the issue:
https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices
