### ISSUE TITLE
if new item entered with same primary key value, prisma unique constrained failed, need to add try catch around prisma calls

### ISSUE THREAD

**Issue by murtaza135** [COOK1EK1W1/deadline-web#36]
![image](https://github.com/COOK1EK1W1/deadline-web/assets/42249079/f65bf897-c490-4b24-bd37-69e5f205c5bb)

**Comment by COOK1EK1W1** [comment]
Should be resolved by adding deadline unique IDs, try catch is a good temporary solution tho
